FROM node:20.6.1
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL 
ENV VITE_SUPABASE_PUBLIC_KEY=$VITE_SUPABASE_PUBLIC_KEY
EXPOSE 5173
CMD ["npm","run","dev"]